G/Client/UI/G.Client.UI.Admin/Controllers/DeployEnvironmentTagController.cs
using G.Client.Business.DeployManage;
using G.Client.Model.DeployManage.DeployEnvironmentTagModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace G.Client.UI.Admin.Controllers
{
    [Authorize]
    public class DeployEnvironmentTagController : Controller
    {
        // GET: DeployEnvironmentTag
        public async Task<ActionResult> Index()
        {
            var lst = await new DeployEnvironmentTagBusiness().GetList();

            return View(lst);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateDeployEnvironmentTagViewModel model)
        {
            ViewBag.IsPostBack = true;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var id = await new DeployEnvironmentTagBusiness().Create(model);

            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var model = await new DeployEnvironmentTagBusiness().GetByID(id);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditDeployEnvironmentTagViewModel model)
        {
            ViewBag.IsPostBack = true;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await new DeployEnvironmentTagBusiness().Update(model);

            return View(model);
        }
    }
}

G/Client/UI/G.Client.UI.Admin/Views/DeployEnvironmentTag/Create.cshtml
@{
    ViewBag.Title = "创建环境标签";
    var allError = ViewData.ModelState.Where(ms => ms.Value.Errors.Count > 0).SelectMany(ms => ms.Value.Errors);
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    @using (Html.BeginForm("Create", "DeployEnvironmentTag", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken();
        <div class="box-body">

            @if (allError.Count() > 0)
            {
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> 错误！</h4>
                    @foreach (var error in allError)
                    {
                        @error.ErrorMessage
                        <br />
                    }
                </div>
            }
            else if (ViewBag.IsPostBack != null && ViewBag.IsPostBack)
            {
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> 成功！</h4>
                </div>
            }

            <div class="form-group">
                <label for="Name" class="col-sm-2 control-label">环境标签</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="Name" name="Name" placeholder="环境标签"><br>
                </div>
            </div>

        </div>
    <!-- /.box-body -->
        <div class="box-footer bg-gray-light">
            <button type="submit" class="btn btn-primary pull-right">保存</button>
        </div>
    <!-- /.box-footer -->
    }
</div>

G/Client/UI/G.Client.UI.Admin/Views/DeployEnvironmentTag/Edit.cshtml
@model G.Client.Model.DeployManage.DeployEnvironmentTagModels.EditDeployEnvironmentTagViewModel
@{
    ViewBag.Title = "编辑环境标签";
    var allError = ViewData.ModelState.Where(ms => ms.Value.Errors.Count > 0).SelectMany(ms => ms.Value.Errors);
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    @using (Html.BeginForm("Edit", "DeployEnvironmentTag", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken();
        <div class="box-body">

            @if (allError.Count() > 0)
            {
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> 错误！</h4>
                    @foreach (var error in allError)
                    {
                        @error.ErrorMessage
                        <br />
                    }
                </div>
            }
            else if (ViewBag.IsPostBack != null && ViewBag.IsPostBack)
            {
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> 成功！</h4>
                </div>
            }

            <div class="form-group">
                <label for="Name" class="col-sm-2 control-label">环境标签</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="Name" name="Name" placeholder="环境标签" value="@Model.Name"><br>
                </div>
            </div>

        </div>
    <!-- /.box-body -->
        <div class="box-footer bg-gray-light">
            <button type="submit" class="btn btn-primary pull-right">保存</button>
        </div>
    <!-- /.box-footer -->
    }
</div>

G/Client/UI/G.Client.UI.Admin/Views/DeployEnvironmentTag/Index.cshtml
@model List<G.Client.Model.DeployManage.DeployEnvironmentTagModels.DeployEnvironmentTagViewModel>
@{
    ViewBag.Title = "环境标签";
}

@section css{
    <link rel="stylesheet" href="~/theme/AdminLTE-2.3.11/extended/ResponsiveTable.css">
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
        <div class="box-tools">
            <div class="input-group input-group-sm">
                <a class="btn btn-block btn-primary btn-sm" href="~/DeployEnvironmentTag/Create">新建</a>
            </div>
        </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 30px" scope="col">#</th>
                    <th scope="col">环境标签</th>
                    <th scope="col">最后修改人</th>
                    <th scope="col">最后修改时间</th>
                    <th style="width: 50px" scope="col">操作</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count == 0)
                {
                    <tr class="text-center text-gray"><td colspan="8"><span style="font-size:30px"><i class="fa fa-warning"></i>&nbsp;没有数据</span></td></tr>
                }
                else
                {
                    for (int i = 0; i < Model.Count; i++)
                    {
                        var et = Model[i];
                        <tr>
                            <td style="vertical-align:middle" data-label="#">@(i + 1).</td>
                            <td style="vertical-align:middle;" data-label="环境标签">@et.Name</td>
                            <td style="vertical-align:middle" data-label="最后修改人">@et.UpdateUserName</td>
                            <td style="vertical-align:middle" data-label="最后修改时间">@et.UpdateTime</td>
                            <td style="vertical-align:middle" data-label="操作">
                                <a class="btn btn-social-icon" style="height:31px" href="~/DeployEnvironmentTag/Edit/@et.ID"><i class="fa fa-edit"></i></a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>