G/Client/UI/G.Client.UI.Admin/Controllers/WindowsPerformanceMonitorController.cs
using G.Client.Business.DeployManage;
using G.Client.Model.DeployManage.WindowsPerformanceMonitorModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace G.Client.UI.Admin.Controllers
{
    [Authorize]
    public class WindowsPerformanceMonitorController : Controller
    {
        // GET: DeploySafetyCheck
        public async Task<ActionResult> Index()
        {
            var lst = await new WindowsPerformanceMonitorBusiness().GetManageViewList();

            return View(lst);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateWindowsPerformanceMonitorViewModel model)
        {
            ViewBag.IsPostBack = true;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var id = await new WindowsPerformanceMonitorBusiness().Create(model);

            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var model = await new WindowsPerformanceMonitorBusiness().GetByID(id);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditWindowsPerformanceMonitorViewModel model)
        {
            ViewBag.IsPostBack = true;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await new WindowsPerformanceMonitorBusiness().Update(model);

            return View(model);
        }

        public async Task<JsonResult> GetByID(int id)
        {
            return new GJsonResult()
            {
                Data = await new WindowsPerformanceMonitorBusiness().GetByID(id),
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
            };
        }
    }
}

G/Client/UI/G.Client.UI.Admin/Views/WindowsPerformanceMonitor/Create.cshtml
@{
    ViewBag.Title = "创建Windows性能监视器";
    var allError = ViewData.ModelState.Where(ms => ms.Value.Errors.Count > 0).SelectMany(ms => ms.Value.Errors);
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    @using (Html.BeginForm("Create", "WindowsPerformanceMonitor", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken();
        <div class="box-body">

            @if (allError.Count() > 0)
            {
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> 错误！</h4>
                    @foreach (var error in allError)
                    {
                        @error.ErrorMessage
                        <br />
                    }
                </div>
            }
            else if (ViewBag.IsPostBack != null && ViewBag.IsPostBack)
            {
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> 成功！</h4>
                </div>
            }

            <div class="form-group">
                <label for="Name" class="col-sm-2 control-label">名称</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="Name" name="Name" placeholder="名称">
                </div>
            </div>

            <div class="form-group">
                <label for="CategoryName" class="col-sm-2 control-label">类别名称</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="CategoryName" name="CategoryName" placeholder="类别名称">
                </div>
            </div>

            <div class="form-group">
                <label for="CounterName" class="col-sm-2 control-label">计数器名称</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="CounterName" name="CounterName" placeholder="计数器名称">
                </div>
            </div>

            <div class="form-group">
                <label for="InstanceName" class="col-sm-2 control-label">实例名称</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="InstanceName" name="InstanceName" placeholder="实例名称">
                </div>
            </div>

            <div class="form-group">
                <label for="MachineName" class="col-sm-2 control-label">
                    计算器名称
                    <i class="fa fa-question-circle" data-toggle="tooltip" title="默认留空，表示自动替换部署服务器IP"></i>
                </label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="MachineName" name="MachineName" placeholder="计算器名称">
                </div>
            </div>

            <div class="form-group">
                <label for="ThresholdValue" class="col-sm-2 control-label">阈值</label>

                <div class="col-sm-9">
                    <input type="text" class="form-control" id="ThresholdValue" name="ThresholdValue" data-mask-decimal>
                </div>
            </div>

        </div>
    <!-- /.box-body -->
        <div class="box-footer bg-gray-light">
            <button type="submit" class="btn btn-primary pull-right">保存</button>
        </div>
    <!-- /.box-footer -->
    }
</div>

@section js{
    <script src="~/theme/AdminLTE-2.3.11/plugins/input-mask/jquery.inputmask.js"></script>
    <script src="~/theme/AdminLTE-2.3.11/plugins/input-mask/jquery.inputmask.numeric.extensions.js"></script>
}

@section initJS{
    <script>
        $("[data-mask-decimal]").inputmask('decimal');
    </script>
}

G/Client/UI/G.Client.UI.Admin/Views/WindowsPerformanceMonitor/Edit.cshtml
@model G.Client.Model.DeployManage.WindowsPerformanceMonitorModels.EditWindowsPerformanceMonitorViewModel
@{
    ViewBag.Title = "编辑Widnows性能监视器";
    var allError = ViewData.ModelState.Where(ms => ms.Value.Errors.Count > 0).SelectMany(ms => ms.Value.Errors);
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    @using (Html.BeginForm("Edit", "WindowsPerformanceMonitor", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken();
        <div class="box-body">

            @if (allError.Count() > 0)
            {
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> 错误！</h4>
                    @foreach (var error in allError)
                    {
                        @error.ErrorMessage
                        <br />
                    }
                </div>
            }
            else if (ViewBag.IsPostBack != null && ViewBag.IsPostBack)
            {
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> 成功！</h4>
                </div>
            }

            <div class="form-group">
                <label for="Name" class="col-sm-2 control-label">名称</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="Name" name="Name" placeholder="名称" value="@Model.Name">
                </div>
            </div>

            <div class="form-group">
                <label for="CategoryName" class="col-sm-2 control-label">类别名称</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="CategoryName" name="CategoryName" placeholder="类别名称" value="@Model.CategoryName">
                </div>
            </div>

            <div class="form-group">
                <label for="CounterName" class="col-sm-2 control-label">计数器名称</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="CounterName" name="CounterName" placeholder="计数器名称" value="@Model.CounterName">
                </div>
            </div>

            <div class="form-group">
                <label for="InstanceName" class="col-sm-2 control-label">实例名称</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="InstanceName" name="InstanceName" placeholder="实例名称" value="@Model.InstanceName">
                </div>
            </div>

            <div class="form-group">
                <label for="MachineName" class="col-sm-2 control-label">
                    计算器名称
                    <i class="fa fa-question-circle" data-toggle="tooltip" title="默认留空，表示自动替换部署服务器IP"></i>
                </label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="MachineName" name="MachineName" placeholder="计算器名称" value="@Model.MachineName">
                </div>
            </div>

            <div class="form-group">
                <label for="ThresholdValue" class="col-sm-2 control-label">阈值</label>

                <div class="col-sm-9">
                    <input type="text" class="form-control" id="ThresholdValue" name="ThresholdValue" data-mask-decimal value="@Model.ThresholdValue">
                </div>
            </div>

        </div>
    <!-- /.box-body -->
        <div class="box-footer bg-gray-light">
            <button type="submit" class="btn btn-primary pull-right">保存</button>
        </div>
    <!-- /.box-footer -->
    }
</div>

@section js{
    <script src="~/theme/AdminLTE-2.3.11/plugins/input-mask/jquery.inputmask.js"></script>
    <script src="~/theme/AdminLTE-2.3.11/plugins/input-mask/jquery.inputmask.numeric.extensions.js"></script>
}

@section initJS{
    <script>
        $("[data-mask-decimal]").inputmask('decimal');
    </script>
}

G/Client/UI/G.Client.UI.Admin/Views/WindowsPerformanceMonitor/Index.cshtml
@model List<G.Client.Model.DeployManage.WindowsPerformanceMonitorModels.WindowsPerformanceMonitorViewModel>
@{
    ViewBag.Title = "Windows性能监视器";
}

@section css{
    <link rel="stylesheet" href="~/theme/AdminLTE-2.3.11/extended/ResponsiveTable.css">
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
        <div class="box-tools">
            <div class="input-group input-group-sm">
                <a class="btn btn-block btn-primary btn-sm" href="~/WindowsPerformanceMonitor/Create">新建</a>
            </div>
        </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 30px" scope="col">#</th>
                    <th scope="col">名称</th>
                    <th scope="col">最后修改人</th>
                    <th scope="col">最后修改时间</th>
                    <th style="width: 50px" scope="col">操作</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count == 0)
                {
                    <tr class="text-center text-gray"><td colspan="8"><span style="font-size:30px"><i class="fa fa-warning"></i>&nbsp;没有数据</span></td></tr>
                }
                else
                {
                    for (int i = 0; i < Model.Count; i++)
                    {
                        var wpm = Model[i];
                        <tr>
                            <td style="vertical-align:middle" data-label="#">@(i + 1).</td>
                            <td style="vertical-align:middle;" data-label="名称">@wpm.Name</td>
                            <td style="vertical-align:middle" data-label="最后修改人">@wpm.UpdateUserName</td>
                            <td style="vertical-align:middle" data-label="最后修改时间">@wpm.UpdateTime</td>
                            <td style="vertical-align:middle" data-label="操作">
                                <a class="btn btn-social-icon" style="height:31px" href="~/WindowsPerformanceMonitor/Edit/@wpm.ID"><i class="fa fa-edit"></i></a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>