G/Client/UI/G.Client.UI.Admin/Controllers/DeployServerController.cs
using G.Client.Business.DeployManage;
using G.Client.Model.DeployManage.DeployServerModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace G.Client.UI.Admin.Controllers
{
    [Authorize]
    public class DeployServerController : Controller
    {
        // GET: DeployManage
        public async Task<ActionResult> Index()
        {
            var deployServerList = await new DeployServerBusiness().GetList();

            return View(deployServerList);
        }

        public async Task<ActionResult> Create()
        {
            ViewBag.DeployEnvironmentList = await new DeployEnvironmentBusiness().GetMangeViewList();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateDeployServerViewModel model)
        {
            ViewBag.IsPostBack = true;
            ViewBag.DeployEnvironmentList = await new DeployEnvironmentBusiness().GetMangeViewList();

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var id = await new DeployServerBusiness().Create(model);

            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var model = await new DeployServerBusiness().GetByID(id);

            ViewBag.DeployEnvironmentList = await new DeployEnvironmentBusiness().GetMangeViewList();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditDeployServerViewModel model)
        {
            ViewBag.IsPostBack = true;
            ViewBag.DeployEnvironmentList = await new DeployEnvironmentBusiness().GetMangeViewList();

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await new DeployServerBusiness().Update(model);

            return View(model);
        }

        public async Task<JsonResult> GetDeployServerListByDeployEnvironmentID(int deployEnvironmentID)
        {
            return new GJsonResult()
            {
                Data = await new DeployServerBusiness().GetDeployServerListByDeployEnvironmentID(deployEnvironmentID),
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }
    }
}

G/Client/UI/G.Client.UI.Admin/Views/DeployServer/Create.cshtml
@{
    ViewBag.Title = "创建服务器";
    bool isFirstRadio = true;
    var allError = ViewData.ModelState.Where(ms => ms.Value.Errors.Count > 0).SelectMany(ms => ms.Value.Errors);
}

@section css{
    <!--iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="~/theme/AdminLTE-2.3.11/plugins/iCheck/all.css">
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    @using (Html.BeginForm("Create", "DeployServer", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken();
        <div class="box-body">

            @if (allError.Count() > 0)
            {
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> 错误！</h4>
                    @foreach (var error in allError)
                    {
                        @error.ErrorMessage
                        <br />
                    }
                </div>
            }
            else if (ViewBag.IsPostBack != null && ViewBag.IsPostBack)
            {
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> 成功！</h4>
                </div>
            }

            <div class="form-group">
                <label for="Name" class="col-sm-2 control-label">服务器名</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="Name" name="Name" placeholder="服务器名"><br>
                </div>
            </div>

            <div class="form-group">
                <label for="ServerIdentity" class="col-sm-2 control-label">服务器标识</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="ServerIdentity" name="ServerIdentity" placeholder="服务器标识"><br>
                </div>
            </div>

            <div class="form-group">
                <label for="IPAddress" class="col-sm-2 control-label">IP地址</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="IPAddress" name="IPAddress" placeholder="IP地址" data-inputmask="'alias': 'ip'" data-mask=""><br>
                </div>
            </div>

            <div class="form-group">
                <label for="Status" class="col-sm-2 control-label">状态</label>

                <div class="col-sm-9">
                    <div style="margin-top:5px;">
                        @foreach (var item in Enum.GetNames(typeof(G.Infrastructure.Constant.Enums.DeployServerStatus)))
                        {
                            var deployServerStatus = (G.Infrastructure.Constant.Enums.DeployServerStatus)Enum.Parse(typeof(G.Infrastructure.Constant.Enums.DeployServerStatus), item);
                            var checkedSign = isFirstRadio ? "checked" : "";
                            isFirstRadio = false;
                            var value = (int)deployServerStatus;
                            <label>
                                <input type="radio" id="Status" value="@value" name="Status" class="minimal" @checkedSign>@deployServerStatus.ToString() &nbsp;&nbsp;
                            </label>
                        }
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="DeployEnvironmentIDList" class="col-sm-2 control-label">部署环境</label>

                <div class="col-sm-9">
                    <div style="margin-top:5px;">
                        @{
                            foreach (var manage in (List<G.Client.Model.DeployManage.DeployEnvironmentModels.DeployEnvironmentManageViewModel>)ViewBag.DeployEnvironmentList)
                            {
                                if (manage.DeployEnvironmentManageItemViewModelList.Count == 0)
                                {
                                    continue;
                                }

                                <h4>@manage.DeployEnvironmentTagName</h4>
                                <hr />
                                foreach (var item in manage.DeployEnvironmentManageItemViewModelList)
                                {
                                    <label>
                                        <input type="checkbox" id="DeployEnvironmentIDList" name="DeployEnvironmentIDList" value="@item.ID" class="minimal">@item.Name &nbsp;&nbsp;
                                    </label>
                                }
                                <br /><br />
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
                            <div class="box-footer bg-gray-light">
                                <button type="submit" class="btn btn-primary pull-right">保存</button>
                            </div>
        <!-- /.box-footer -->
                            }

</div>

@section js{
    <!-- iCheck 1.0.1 -->
    <script src="~/theme/AdminLTE-2.3.11/plugins/iCheck/icheck.min.js"></script>
    <script src="~/theme/AdminLTE-2.3.11/plugins/input-mask/jquery.inputmask.js"></script>
    <script src="~/theme/AdminLTE-2.3.11/plugins/input-mask/jquery.inputmask.extensions.js"></script>
}

@section initJS{
    <script>
        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-blue',
            radioClass: 'iradio_minimal-blue'
        });

        $("[data-mask]").inputmask();
    </script>
}

G/Client/UI/G.Client.UI.Admin/Views/DeployServer/Edit.cshtml
@model G.Client.Model.DeployManage.DeployServerModels.EditDeployServerViewModel
@{
    ViewBag.Title = "编辑服务器";
    var allError = ViewData.ModelState.Where(ms => ms.Value.Errors.Count > 0).SelectMany(ms => ms.Value.Errors);
}

@section css{
    <!--iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="~/theme/AdminLTE-2.3.11/plugins/iCheck/all.css">
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    @using (Html.BeginForm("Edit", "DeployServer", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken();
        <div class="box-body">

            @if (allError.Count() > 0)
            {
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> 错误！</h4>
                    @foreach (var error in allError)
                    {
                        @error.ErrorMessage
                        <br />
                    }
                </div>
            }
            else if (ViewBag.IsPostBack != null && ViewBag.IsPostBack)
            {
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> 成功！</h4>
                </div>
            }

            <div class="form-group">
                <label for="Name" class="col-sm-2 control-label">服务器名</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="Name" name="Name" placeholder="服务器名" value="@Model.Name">
                </div>
            </div>

            <div class="form-group">
                <label for="ServerIdentity" class="col-sm-2 control-label">服务器标识</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="ServerIdentity" name="ServerIdentity" placeholder="服务器标识" value="@Model.ServerIdentity">
                </div>
            </div>

            <div class="form-group">
                <label for="IPAddress" class="col-sm-2 control-label">IP地址</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="IPAddress" name="IPAddress" placeholder="IP地址" value="@Model.IPAddress" data-inputmask="'alias': 'ip'" data-mask="">
                </div>
            </div>

            <div class="form-group">
                <label for="Status" class="col-sm-2 control-label">状态</label>

                <div class="col-sm-9">
                    <div style="margin-top:5px;">
                        @foreach (var item in Enum.GetNames(typeof(G.Infrastructure.Constant.Enums.DeployServerStatus)))
                        {
                            var deployServerStatus = (G.Infrastructure.Constant.Enums.DeployServerStatus)Enum.Parse(typeof(G.Infrastructure.Constant.Enums.DeployServerStatus), item);
                            var checkedSign = deployServerStatus == Model.Status ? "checked" : "";
                            var value = (int)deployServerStatus;
                            <label>
                                <input type="radio" id="Status" value="@value" name="Status" class="minimal" @checkedSign>@deployServerStatus.ToString() &nbsp;&nbsp;
                            </label>
                        }
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="DeployEnvironmentID" class="col-sm-2 control-label">部署环境</label>

                <div class="col-sm-9">
                    <div style="margin-top:5px;">
                        @{
                            foreach (var manage in (List<G.Client.Model.DeployManage.DeployEnvironmentModels.DeployEnvironmentManageViewModel>)ViewBag.DeployEnvironmentList)
                            {
                                if (manage.DeployEnvironmentManageItemViewModelList.Count == 0)
                                {
                                    continue;
                                }

                                <h4>@manage.DeployEnvironmentTagName</h4>
                                <hr />
                                foreach (var item in manage.DeployEnvironmentManageItemViewModelList)
                                {
                                    var checkedSign = Model.DeployEnvironmentIDList.Contains(item.ID) ? " checked" : "";
                                    <label>
                                        <input type="checkbox" id="DeployEnvironmentIDList" name="DeployEnvironmentIDList" value="@item.ID" class="minimal" @checkedSign>@item.Name &nbsp;&nbsp;
                                    </label>
                                }
                                <br /><br />
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
            <!-- /.box-body -->
                            <div class="box-footer bg-gray-light">
                                <button type="submit" class="btn btn-primary pull-right">保存</button>
                            </div>
            <!-- /.box-footer -->
                            }

</div>

@section js{
    <!-- iCheck 1.0.1 -->
    <script src="~/theme/AdminLTE-2.3.11/plugins/iCheck/icheck.min.js"></script>
    <script src="~/theme/AdminLTE-2.3.11/plugins/input-mask/jquery.inputmask.js"></script>
    <script src="~/theme/AdminLTE-2.3.11/plugins/input-mask/jquery.inputmask.extensions.js"></script>
}

@section initJS{
    <script>
        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-blue',
            radioClass: 'iradio_minimal-blue'
        });

        $("[data-mask]").inputmask();
    </script>
}

G/Client/UI/G.Client.UI.Admin/Views/DeployServer/Index.cshtml
@model List<G.Client.Model.DeployManage.DeployServerModels.DeployServerViewModel>
@{
    ViewBag.Title = "服务器";
}

@section css{
    <link rel="stylesheet" href="~/theme/AdminLTE-2.3.11/extended/ResponsiveTable.css">
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
        <div class="box-tools">
            <div class="input-group input-group-sm">
                <a class="btn btn-block btn-primary btn-sm" href="~/DeployServer/Create">新建</a>
            </div>
        </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 30px" scope="col">#</th>
                    <th scope="col">服务器名</th>
                    <th scope="col">服务器标识</th>
                    <th scope="col">IP地址</th>
                    <th scope="col">状态</th>
                    <th scope="col">最后修改人</th>
                    <th scope="col">最后修改时间</th>
                    <th style="width: 50px" scope="col">操作</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count == 0)
                {
                    <tr class="text-center text-gray"><td colspan="9"><span style="font-size:30px"><i class="fa fa-warning"></i>&nbsp;没有数据</span></td></tr>
                }
                else
                {
                    for (int i = 0; i < Model.Count; i++)
                    {
                        var server = Model[i];
                        <tr>
                            <td style="vertical-align:middle" data-label="#">@(i + 1).</td>
                            <td style="vertical-align:middle;" data-label="服务器名">@server.Name</td>
                            <td style="vertical-align:middle" data-label="服务器标识">@server.ServerIdentity</td>
                            <td style="vertical-align:middle" data-label="IP地址">@server.IPAddress</td>
                            <td style="vertical-align:middle" data-label="状态">
                                @switch (server.Status)
                                {
                                    case G.Infrastructure.Constant.Enums.DeployServerStatus.Online:
                                        <span class="label label-success">@server.Status</span>
                                        break;
                                    case G.Infrastructure.Constant.Enums.DeployServerStatus.Offline:
                                        <span class="label label-danger">@server.Status</span>
                                        break;
                                    default:
                                        break;
                                }
                            </td>
                            <td style="vertical-align:middle" data-label="最后修改人">@server.UpdateUserName</td>
                            <td style="vertical-align:middle" data-label="最后修改时间">@server.UpdateTime</td>
                            <td style="vertical-align:middle" data-label="操作">
                                <a class="btn btn-social-icon" style="height:31px" href="~/DeployServer/Edit/@server.ID"><i class="fa fa-edit"></i></a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>