G/Client/UI/G.Client.UI.Admin/Controllers/DeployEnvironmentController.cs
using G.Client.Business.DeployManage;
using G.Client.Model.DeployManage.DeployEnvironmentModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace G.Client.UI.Admin.Controllers
{
    [Authorize]
    public class DeployEnvironmentController : Controller
    {
        // GET: DeployEnvironmentManage
        public async Task<ActionResult> Index()
        {
            var lst = await new DeployEnvironmentBusiness().GetMangeViewList();

            return View(lst);
        }

        public async Task<ActionResult> Create()
        {
            await InitOptionsData();

            return View();
        }

        private async Task InitOptionsData()
        {
            ViewBag.DeployProjectList = await new DeployProjectBusiness().GetList();
            ViewBag.DeployEnvironmentTagList = await new DeployEnvironmentTagBusiness().GetList();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateDeployEnvironmentViewModel model)
        {
            ViewBag.IsPostBack = true;
            await InitOptionsData();

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var id = await new DeployEnvironmentBusiness().Create(model);

            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var model = await new DeployEnvironmentBusiness().GetByID(id);

            await InitOptionsData();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditDeployEnvironmentViewModel model)
        {
            ViewBag.IsPostBack = true;
            await InitOptionsData();

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await new DeployEnvironmentBusiness().Update(model);

            return View(model);
        }
    }
}

G/Client/UI/G.Client.UI.Admin/Views/DeployEnvironment/Create.cshtml
@{
    ViewBag.Title = "创建环境";
    var allError = ViewData.ModelState.Where(ms => ms.Value.Errors.Count > 0).SelectMany(ms => ms.Value.Errors);
}

@section css{
    <!-- Select2 -->
    <link rel="stylesheet" href="~/theme/AdminLTE-2.3.11/plugins/select2/select2.min.css">
    <link rel="stylesheet" href="~/theme/AdminLTE-2.3.11/dist/css/AdminLTE.min.css">
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    @using (Html.BeginForm("Create", "DeployEnvironment", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken();
        <div class="box-body">

            @if (allError.Count() > 0)
            {
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> 错误！</h4>
                    @foreach (var error in allError)
                    {
                        @error.ErrorMessage
                        <br />
                    }
                </div>
            }
            else if (ViewBag.IsPostBack != null && ViewBag.IsPostBack)
            {
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> 成功！</h4>
                </div>
            }

            <div class="form-group">
                <label for="Name" class="col-sm-2 control-label">环境名称</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="Name" name="Name" placeholder="环境名称">
                </div>
            </div>

            <div class="form-group">
                <label for="DeployEnvironmentTagID" class="col-sm-2 control-label">环境标签</label>

                <div class="col-sm-9">
                    <select class="form-control select2" style="width: 100%;" id="DeployEnvironmentTagID" name="DeployEnvironmentTagID">
                        @{
                            for (int i = 0; i < ViewBag.DeployEnvironmentTagList.Count; i++)
                            {
                                var selected = i == 0 ? "selected=\"selected\"" : "";
                                <option @selected value="@ViewBag.DeployEnvironmentTagList[i].ID">@ViewBag.DeployEnvironmentTagList[i].Name</option>
                            }
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="DeployProjectID" class="col-sm-2 control-label">项目</label>

                <div class="col-sm-9">
                    <select class="form-control select2" style="width: 100%;" id="DeployProjectID" name="DeployProjectID">
                        @{
                            for (int i = 0; i < ViewBag.DeployProjectList.Count; i++)
                            {
                                var selected = i == 0 ? "selected=\"selected\"" : "";
                                <option @selected value="@ViewBag.DeployProjectList[i].ID">@ViewBag.DeployProjectList[i].Name</option>
                            }
                        }
                    </select>
                </div>
            </div>            

        </div>
    <!-- /.box-body -->
                            <div class="box-footer bg-gray-light">
                                <button type="submit" class="btn btn-primary pull-right">保存</button>
                            </div>
    <!-- /.box-footer -->
                            }
    
</div>

@section js{
    <!-- Select2 -->
    <script src="~/theme/AdminLTE-2.3.11/plugins/select2/select2.full.min.js"></script>
}

@section initJS{
    <script>
        $(function () {
            //Initialize Select2 Elements
            $(".select2").select2();
        })
    </script>
}

G/Client/UI/G.Client.UI.Admin/Views/DeployEnvironment/Edit.cshtml
@model G.Client.Model.DeployManage.DeployEnvironmentModels.EditDeployEnvironmentViewModel
@{
    ViewBag.Title = "编辑环境";
    var allError = ViewData.ModelState.Where(ms => ms.Value.Errors.Count > 0).SelectMany(ms => ms.Value.Errors);
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    @using (Html.BeginForm("Edit", "DeployEnvironment", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken();
        <div class="box-body">

            @if (allError.Count() > 0)
            {
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> 错误！</h4>
                    @foreach (var error in allError)
                    {
                        @error.ErrorMessage
                        <br />
                    }
                </div>
            }
            else if (ViewBag.IsPostBack != null && ViewBag.IsPostBack)
            {
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> 成功！</h4>
                </div>
            }

            <div class="form-group">
                <label for="Name" class="col-sm-2 control-label">环境名称</label>

                <div class="col-sm-9">
                    <input class="form-control" type="text" id="Name" name="Name" placeholder="环境名称" value="@Model.Name">
                </div>
            </div>

            <div class="form-group">
                <label for="DeployEnvironmentTagID" class="col-sm-2 control-label">环境标签</label>

                <div class="col-sm-9">
                    <select class="form-control select2" style="width: 100%;" id="DeployEnvironmentTagID" name="DeployEnvironmentTagID">
                        @{
                            for (int i = 0; i < ViewBag.DeployEnvironmentTagList.Count; i++)
                            {
                                var selected = ViewBag.DeployEnvironmentTagList[i].ID == Model.DeployEnvironmentTagID ? "selected=\"selected\"" : "";
                                <option @selected value="@ViewBag.DeployEnvironmentTagList[i].ID">@ViewBag.DeployEnvironmentTagList[i].Name</option>
                            }
                        }
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="DeployProjectID" class="col-sm-2 control-label">项目</label>

                <div class="col-sm-9">
                    <select class="form-control select2" style="width: 100%;" id="DeployProjectID" name="DeployProjectID">
                        @{
                            for (int i = 0; i < ViewBag.DeployProjectList.Count; i++)
                            {
                                var selected = ViewBag.DeployProjectList[i].ID == Model.DeployProjectID ? "selected=\"selected\"" : "";
                                <option @selected value="@ViewBag.DeployProjectList[i].ID">@ViewBag.DeployProjectList[i].Name</option>
                            }
                        }
                    </select>
                </div>
            </div>

        </div>
    <!-- /.box-body -->
                            <div class="box-footer bg-gray-light">
                                <button type="submit" class="btn btn-primary pull-right">保存</button>
                            </div>
    <!-- /.box-footer -->
                            }
    
</div>

G/Client/UI/G.Client.UI.Admin/Views/DeployEnvironment/Index.cshtml
@model List<G.Client.Model.DeployManage.DeployEnvironmentModels.DeployEnvironmentManageViewModel>
@{
    ViewBag.Title = "环境";
}

@section css{
    <link rel="stylesheet" href="~/theme/AdminLTE-2.3.11/extended/ResponsiveTable.css">
    <link rel="stylesheet" href="~/theme/AdminLTE-2.3.11/extended/BoxPatch.css">
}

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        @for (int i = 0; i < Model.Count; i++)
        {
            var className = i == 0 ? "active" : "";
            var ariaExpanded = i == 0 ? true : false;

            <li class="@className"><a href="#@Model[i].DeployEnvironmentTagID" data-toggle="tab" aria-expanded="@ariaExpanded.ToString()">@Model[i].DeployEnvironmentTagName</a></li>
        }

        @if (Model.Count == 0)
        {
            <li class="active"><a href="#0" data-toggle="tab" aria-expanded="true">无</a></li>
        }
        <li class="pull-right">
            <buttton type="buttton" class="btn btn-block btn-primary btn-sm" style="margin-top:3px;" onclick="javascript: window.location='/DeployEnvironment/Create'">新建环境</buttton>
        </li>
    </ul>
    <div class="tab-content">

        @if (Model.Count == 0)
        {
            <div style="text-align:center">
                <span style="font-size:30px;color:#777"><i class="fa fa-warning"></i>&nbsp;请先创建环境标签</span>
            </div>
        }
        else
        {
            for (int i = 0; i < Model.Count; i++)
            {
                var className = i == 0 ? "active" : "";

                <div class="tab-pane @className" id="@Model[i].DeployEnvironmentTagID">

                    @if (Model[i].DeployEnvironmentManageItemViewModelList.Count == 0)
                    {
                        <div style="text-align:center">
                            <span style="font-size:30px;color:#777"><i class="fa fa-warning"></i>&nbsp;本环境标签内没有环境</span>
                        </div>
                    }

                    @foreach (var item in Model[i].DeployEnvironmentManageItemViewModelList)
                    {
                        <div class="box box-group box-solid bg-light-blue-gradient" style="position: relative;">
                            <div class="box-header ui-sortable-handle">
                                <!-- tools box -->
                                <div class="pull-right box-tools">
                                    <button type="button" class="btn btn-primary btn-sm pull-right" data-toggle="tooltip" title="修改" style="cursor:pointer" onclick="javascript: window.location.href='/DeployEnvironment/Edit/@item.ID'">
                                        <i class="fa fa-edit"></i>
                                    </button>
                                    <button type="button" class="btn btn-primary btn-sm pull-right" data-widget="collapse" data-toggle="tooltip" title="最小化" style="margin-right: 5px;">
                                        <i class="fa fa-minus"></i>
                                    </button>
                                </div>
                                <!-- /. tools -->

                                <i class="fa fa-paw"></i>

                                <h3 class="box-title">
                                    @item.Name
                                </h3>
                            </div>
                            <div class="box-body" style="border:1px solid #3C8DBC;border-top:none">
                                <span class="label label-danger" style="cursor:pointer" onclick="javascript: window.location='/DeployProject/Edit/@item.DeployProjectID'">@item.DeployProjectName</span>
                            </div>
                            <!-- /.box-body-->
                            <div class="box-footer" style="border:1px solid #3C8DBC;border-top:none">
                                <div class="row">
                                    @if (item.DeployServerList.Count == 0)
                                    {
                                        <div style="text-align:center;color:#777">
                                            <span style="font-size:30px"><i class="fa fa-warning"></i>&nbsp;本环境内没有服务器</span>
                                        </div>
                                    }

                                    @foreach (var ds in item.DeployServerList)
                                    {
                                        <div class="project-item text-center" style="cursor:pointer;" onclick="javascript:window.location.href='/DeployServer/Edit/@ds.ID'" data-toggle="tooltip" title="编辑服务器">
                                            <div class="row">
                                                <img src="~/theme/AdminLTE-2.3.11/img/server.png" />
                                            </div>
                                            <div class="row">
                                                <a class="name">@ds.Name</a>
                                            </div>

                                        </div>
                                    <!-- ./col -->
                                    }
                                </div>
                                <!-- /.row -->
                            </div>
                        </div>
                    }
                </div>
            }
        }

        <!-- /.tab-pane -->
    </div>
    <!-- /.tab-content -->
</div>